[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "ninja",
    "cmake>=3.22",
]
build-backend = "setuptools.build_meta"


[tool.cibuildwheel]
before-build = "rm -rf {project}/build"

[tool.cibuildwheel.linux]
before-all = "yum install -y gmp-devel mpfr-devel"